-- Удаление таблицы
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.locations CASCADE;
DROP TABLE IF EXISTS public.events CASCADE;
DROP TABLE IF EXISTS public.compilations CASCADE;
DROP TABLE IF EXISTS public.compilation_events CASCADE;
DROP TABLE IF EXISTS public.requests CASCADE;
DROP TABLE IF EXISTS public.comments CASCADE;

-- Создание таблицы users
CREATE TABLE IF NOT EXISTS users (
    id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) UNIQUE NOT NULL,
    name  VARCHAR(250)        NOT NULL
);

-- Создание таблицы categories
CREATE TABLE IF NOT EXISTS public.categories (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

-- Создание таблицы events
CREATE TABLE IF NOT EXISTS public.events (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation         TEXT          NOT NULL,
    category_id        bigint        NOT NULL,
    description        TEXT          NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    lat                DECIMAL(8, 6) CHECK (lat >= -90 AND lat <= 90),
    lon                DECIMAL(9, 6) CHECK (lon >= -180 AND lon <= 180),
    paid               BOOLEAN       NOT NULL DEFAULT FALSE,
    participant_limit  INTEGER                DEFAULT 0,
    request_moderation BOOLEAN       NOT NULL DEFAULT TRUE,
    title              VARCHAR(120)  NOT NULL,
    initiator_id       bigint        NOT NULL,
    created_on         TIMESTAMP              DEFAULT CURRENT_TIMESTAMP,
    published_on       TIMESTAMP,
    state              VARCHAR(20)            DEFAULT 'PENDING',
    confirmed_requests INTEGER                DEFAULT 0,
    views              bigint                 DEFAULT 0,
    comments           INTEGER                DEFAULT 0,

    CONSTRAINT fk_events_category FOREIGN KEY (category_id) REFERENCES public.categories (id) ON DELETE CASCADE,
    CONSTRAINT fk_events_initiator FOREIGN KEY (initiator_id) REFERENCES public.users (id) ON DELETE CASCADE
);

-- Создание таблицы requests
CREATE TABLE IF NOT EXISTS public.requests (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     bigint NOT NULL,
    created      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    requester_id bigint NOT NULL,
    status       VARCHAR(20) DEFAULT 'PENDING',

    CONSTRAINT fk_event_id FOREIGN KEY (event_id) REFERENCES public.events (id) ON DELETE CASCADE,
    CONSTRAINT fk_requester_id FOREIGN KEY (requester_id) REFERENCES public.users (id) ON DELETE CASCADE
);

-- Создание таблицы compilations
CREATE TABLE IF NOT EXISTS public.compilations (
    id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title  VARCHAR(50)  NOT NULL UNIQUE,
    pinned BOOLEAN      NOT NULL DEFAULT false
);

-- Создание таблицы compilation_events
CREATE TABLE IF NOT EXISTS public.compilation_events (
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,

    PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT fk_compilation_events_compilation FOREIGN KEY (compilation_id)
        REFERENCES public.compilations (id) ON DELETE CASCADE,
    CONSTRAINT fk_compilation_events_event FOREIGN KEY (event_id) REFERENCES public.events (id) ON DELETE CASCADE
);

-- Создание таблицы comments
CREATE TABLE IF NOT EXISTS comments (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    bigint                      NOT NULL,
    text        TEXT                        NOT NULL,
    user_id     bigint                      NOT NULL,
    create_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT fk_event_id FOREIGN KEY (event_id) REFERENCES public.events (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE
);