-- Удаление таблицы
DROP TABLE IF EXISTS PUBLIC.hits CASCADE;

-- Создание таблицы hits
CREATE TABLE IF NOT EXISTS hits (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app       VARCHAR(255) NOT NULL,
    uri       VARCHAR(255) NOT NULL,
    ip        VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);